/** Mirrors `app/lib/features/checklist/data/static_task_catalog.dart`. */
export const defaultTaskCatalog = [
  { id: 'fajr_waking_up_adhkar', category: 'fajr', points: 2 },
  { id: 'fajr_sunnah_before_fajr', category: 'fajr', points: 2 },
  { id: 'fajr_first_congregation', category: 'fajr', points: 2 },
  { id: 'fajr_post_prayer_adhkar', category: 'fajr', points: 2 },
  { id: 'fajr_morning_adhkar', category: 'fajr', points: 2 },
  { id: 'fajr_duha_4_rakahs', category: 'fajr', points: 2 },
  { id: 'dhuhr_sunnah_before_4_rakahs', category: 'dhuhr', points: 2 },
  { id: 'dhuhr_first_congregation', category: 'dhuhr', points: 2 },
  { id: 'dhuhr_post_prayer_adhkar', category: 'dhuhr', points: 2 },
  { id: 'dhuhr_sunnah_after', category: 'dhuhr', points: 2 },
  { id: 'asr_first_congregation', category: 'asr', points: 2 },
  { id: 'asr_post_prayer_adhkar', category: 'asr', points: 2 },
  { id: 'asr_evening_adhkar', category: 'asr', points: 2 },
  { id: 'maghrib_first_congregation', category: 'maghrib', points: 2 },
  { id: 'maghrib_post_prayer_adhkar', category: 'maghrib', points: 2 },
  { id: 'maghrib_sunnah_after', category: 'maghrib', points: 2 },
  { id: 'isha_first_congregation', category: 'isha', points: 2 },
  { id: 'isha_post_prayer_adhkar', category: 'isha', points: 2 },
  { id: 'isha_sunnah_after', category: 'isha', points: 2 },
  { id: 'qiyam_two_rakahs', category: 'qiyamEvening', points: 4 },
  { id: 'qiyam_daily_quran_two_quarters', category: 'qiyamEvening', points: 4 },
  { id: 'qiyam_witr', category: 'qiyamEvening', points: 1 },
  { id: 'qiyam_adhkar_before_sleep', category: 'qiyamEvening', points: 2 },
  { id: 'quran_memorize_half_page', category: 'quranFasting', points: 2 },
  { id: 'quran_read_six_quarters', category: 'quranFasting', points: 2 },
  { id: 'quran_fasting_mon_thu', category: 'quranFasting', points: 5 },
  { id: 'misc_restroom_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_clothing_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_wudu_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_house_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_mosque_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_walking_mosque_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_eating_drinking_adhkar', category: 'miscAdhkar', points: 2 },
  { id: 'misc_riding_traveling_adhkar', category: 'miscAdhkar', points: 2 },
] as const;
