/** Mirrors Flutter static catalog + category metadata. */
export const defaultCategoriesSeed = [
  { code: 'fajr', defaultName: 'Fajr', defaultIcon: 'wb_twilight', defaultSortOrder: 0, isFard: true },
  { code: 'dhuhr', defaultName: 'Dhuhr', defaultIcon: 'wb_sunny', defaultSortOrder: 1, isFard: true },
  { code: 'asr', defaultName: 'Asr', defaultIcon: 'partly_cloudy_day', defaultSortOrder: 2, isFard: true },
  { code: 'maghrib', defaultName: 'Maghrib', defaultIcon: 'wb_twilight', defaultSortOrder: 3, isFard: true },
  { code: 'isha', defaultName: 'Isha', defaultIcon: 'nights_stay', defaultSortOrder: 4, isFard: true },
  { code: 'qiyamEvening', defaultName: 'Qiyam & Evening', defaultIcon: 'bedtime', defaultSortOrder: 5, isFard: false },
  { code: 'quranFasting', defaultName: 'Quran & Fasting', defaultIcon: 'menu_book', defaultSortOrder: 6, isFard: false },
  { code: 'miscAdhkar', defaultName: 'Misc Adhkar', defaultIcon: 'auto_awesome', defaultSortOrder: 7, isFard: false },
] as const;

export const defaultTasksSeed = [
  { id: 'fajr_waking_up_adhkar', categoryCode: 'fajr', defaultPoints: 2, defaultSortOrder: 0 },
  { id: 'fajr_sunnah_before_fajr', categoryCode: 'fajr', defaultPoints: 2, defaultSortOrder: 1 },
  { id: 'fajr_first_congregation', categoryCode: 'fajr', defaultPoints: 2, defaultSortOrder: 2 },
  { id: 'fajr_post_prayer_adhkar', categoryCode: 'fajr', defaultPoints: 2, defaultSortOrder: 3 },
  { id: 'fajr_morning_adhkar', categoryCode: 'fajr', defaultPoints: 2, defaultSortOrder: 4 },
  { id: 'fajr_duha_4_rakahs', categoryCode: 'fajr', defaultPoints: 2, defaultSortOrder: 5 },
  { id: 'dhuhr_sunnah_before_4_rakahs', categoryCode: 'dhuhr', defaultPoints: 2, defaultSortOrder: 6 },
  { id: 'dhuhr_first_congregation', categoryCode: 'dhuhr', defaultPoints: 2, defaultSortOrder: 7 },
  { id: 'dhuhr_post_prayer_adhkar', categoryCode: 'dhuhr', defaultPoints: 2, defaultSortOrder: 8 },
  { id: 'dhuhr_sunnah_after', categoryCode: 'dhuhr', defaultPoints: 2, defaultSortOrder: 9 },
  { id: 'asr_first_congregation', categoryCode: 'asr', defaultPoints: 2, defaultSortOrder: 10 },
  { id: 'asr_post_prayer_adhkar', categoryCode: 'asr', defaultPoints: 2, defaultSortOrder: 11 },
  { id: 'asr_evening_adhkar', categoryCode: 'asr', defaultPoints: 2, defaultSortOrder: 12 },
  { id: 'maghrib_first_congregation', categoryCode: 'maghrib', defaultPoints: 2, defaultSortOrder: 13 },
  { id: 'maghrib_post_prayer_adhkar', categoryCode: 'maghrib', defaultPoints: 2, defaultSortOrder: 14 },
  { id: 'maghrib_sunnah_after', categoryCode: 'maghrib', defaultPoints: 2, defaultSortOrder: 15 },
  { id: 'isha_first_congregation', categoryCode: 'isha', defaultPoints: 2, defaultSortOrder: 16 },
  { id: 'isha_post_prayer_adhkar', categoryCode: 'isha', defaultPoints: 2, defaultSortOrder: 17 },
  { id: 'isha_sunnah_after', categoryCode: 'isha', defaultPoints: 2, defaultSortOrder: 18 },
  { id: 'qiyam_two_rakahs', categoryCode: 'qiyamEvening', defaultPoints: 4, defaultSortOrder: 19 },
  { id: 'qiyam_daily_quran_two_quarters', categoryCode: 'qiyamEvening', defaultPoints: 4, defaultSortOrder: 20 },
  { id: 'qiyam_witr', categoryCode: 'qiyamEvening', defaultPoints: 1, defaultSortOrder: 21 },
  { id: 'qiyam_adhkar_before_sleep', categoryCode: 'qiyamEvening', defaultPoints: 2, defaultSortOrder: 22 },
  { id: 'quran_memorize_half_page', categoryCode: 'quranFasting', defaultPoints: 2, defaultSortOrder: 23 },
  { id: 'quran_read_six_quarters', categoryCode: 'quranFasting', defaultPoints: 2, defaultSortOrder: 24 },
  { id: 'quran_fasting_mon_thu', categoryCode: 'quranFasting', defaultPoints: 5, defaultSortOrder: 25 },
  { id: 'misc_restroom_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 26 },
  { id: 'misc_clothing_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 27 },
  { id: 'misc_wudu_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 28 },
  { id: 'misc_house_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 29 },
  { id: 'misc_mosque_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 30 },
  { id: 'misc_walking_mosque_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 31 },
  { id: 'misc_eating_drinking_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 32 },
  { id: 'misc_riding_traveling_adhkar', categoryCode: 'miscAdhkar', defaultPoints: 2, defaultSortOrder: 33 },
] as const;
