import 'package:flutter/material.dart';

/// Maps curated icon code strings to [IconData] (Material Symbols style).
IconData curatedIconData(String code) {
  return switch (code) {
    'mosque' => Icons.mosque_outlined,
    'book_5' => Icons.menu_book_outlined,
    'sunny' => Icons.wb_sunny_outlined,
    'nights_stay' => Icons.nights_stay_outlined,
    'volunteer_activism' => Icons.volunteer_activism_outlined,
    'self_improvement' => Icons.self_improvement_outlined,
    'favorite' => Icons.favorite_outline,
    'auto_awesome' => Icons.auto_awesome_outlined,
    'local_florist' => Icons.local_florist_outlined,
    'water_drop' => Icons.water_drop_outlined,
    'wb_twilight' => Icons.wb_twilight_outlined,
    'dark_mode' => Icons.dark_mode_outlined,
    'light_mode' => Icons.light_mode_outlined,
    'schedule' => Icons.schedule_outlined,
    'alarm' => Icons.alarm_outlined,
    'notifications' => Icons.notifications_outlined,
    'menu_book' => Icons.menu_book_outlined,
    'bookmark' => Icons.bookmark_outline,
    'star' => Icons.star_outline,
    'check_circle' => Icons.check_circle_outline,
    'radio_button_unchecked' => Icons.radio_button_unchecked,
    'flag' => Icons.flag_outlined,
    'bolt' => Icons.bolt_outlined,
    'eco' => Icons.eco_outlined,
    'spa' => Icons.spa_outlined,
    'psychology' => Icons.psychology_outlined,
    'lightbulb' => Icons.lightbulb_outline,
    'coffee' => Icons.coffee_outlined,
    'restaurant' => Icons.restaurant_outlined,
    'bedtime' => Icons.bedtime_outlined,
    'wb_sunny' => Icons.wb_sunny_outlined,
    'partly_cloudy_day' => Icons.wb_cloudy_outlined,
    'family_restroom' => Icons.family_restroom_outlined,
    'groups' => Icons.groups_outlined,
    'phone' => Icons.phone_outlined,
    'chat' => Icons.chat_outlined,
    'directions_walk' => Icons.directions_walk_outlined,
    'directions_run' => Icons.directions_run_outlined,
    'fitness_center' => Icons.fitness_center_outlined,
    'library_books' => Icons.library_books_outlined,
    _ => Icons.star_outline,
  };
}
